# The given playbook attempts to start mysql service on all_servers. Use the when condition to run this task if the host (ansible_host) is the database server.
# Refer to the inventory file to identify the name of the database server.

# ------------------------------
#           BEFORE
# ------------------------------
#-
#  name: Execute a script on all web server nodes
#  hosts: all_servers
#  tasks:
#    -
#      service: name=mysql state=started
#
# ------------------------------
#           AFTER
# ------------------------------
---
  
 - hosts: web_nodes
   remote_user: root 
   tasks:
     - name: check mysql is installed
       service: 
          name: mysql
          state: started
       when: ansible_host=='172.31.21.89'
       ignore_errors: yes
     - name: debugging
       debug: msg={{ ansible_host }}

...

