---
- name: create an EC2 Instance
  ec2:
    key_name: "{{ keypair }}"
    aws_access_key: "{{ my_access_key }}"
    aws_secret_key: "{{ my_secret_key }}"
    group: "AWS-demo-RHEL7.5-security-group"
    instance_type: t2.micro
    image: "{{ ami }}" 
    wait: true
    region: "{{ region }}"
    count: 1
    count_tag: 
      Name: "Ansible_Demo1_Ec2"
    instance_tags:
      Name: "Demo_Ansible"
    vpc_subnet_id: subnet-df637695
    assign_public_ip: yes
  register: ec2
- name: Debug EC2 creation
  debug: var=ec2
- name: Get Private IP
  debug:
    msg: "{{ item['private_ip'] }}"
  with_items: "{{ ec2.instances }}"
- name: Add all instance Private IP in hosts
  add_host: 
     hostname: "{{ item.private_ip }}"
     groupname: webservers
     ansible_user: ec2-user
  with_items: "{{ ec2.instances }}"
#- name: add public key of controle to remote machine
#  authorized_key:
#      user: root
#      state: present
#      key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
- name: Wait for ssh to come up
  wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
  with_items: "{{ ec2.instances }}"

  
    
